### ISSUE TITLE
重新调研下机器人软件框架，参考下列表格，把提到的软件框架中有对应论文的都把论文下载链接列出来

### ISSUE THREAD

**Issue by jiuyewxy** [Akana-kunama/PLCT_Kunama#1]
机器人框架汇总：https://agrobofood.github.io/agrobofood-case-studies/case_studies/Robot-Software-Platforms.html

- 论文下载链接
- 开源项目链接
- 论文摘要翻译

**Comment by Akana-kunama** [comment]
https://github.com/Akana-kunama/PLCT_Kunama/blob/main/issue8/issue8_report.md
老师你看这样成不

**Comment by jiuyewxy** [comment]
可以，这个任务到目前为止算完成，后续有新的需求会开新任务
